data:
  AzureWebJobsStorage: <>
  AzureWebJobsServiceBus__credential: <>
  AzureWebJobsServiceBus__fullyQualifiedNamespace: <>
  AzureWebJobsServiceBus__clientId: <>
  FUNCTIONS_WORKER_RUNTIME: <>
apiVersion: v1
kind: Secret
metadata:
  name: <>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: <>
  labels:
    app: <>
spec:
  selector:
    matchLabels:
      app: <>
  template:
    metadata:
      labels:
        app: <>
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: workload-identity-sa
      containers:
      - name:<>
        image: <>
        env:
        - name: AzureFunctionsJobHost__functions__0
          value: <>
        envFrom:
        - secretRef:
            name: <>
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
        startupProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: kedafuncsbtrigauth
  namespace: default # must be same namespace as the ScaledObject
spec:
  podIdentity:
      provider:  azure-workload  # Optional. Default: none
      identityId: <>
---      
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: <>
  labels: {}
spec:
  scaleTargetRef:
    name: <>
  triggers:
  - type: azure-servicebus
    metadata:
      direction: In
      queueName:<>
      namespace: <>
      cardinality: One
    authenticationRef:
      name: kedafuncsbtrigauth  
---

